"""application model updated_at included

Revision ID: 226e7b6a47cd
Revises: 381cdcc9d333
Create Date: 2026-10-04 08:51:48.385778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226e7b6a47cd'
down_revision: Union[str, Sequence[str], None] = '381cdcc9d333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'updated_at')
    # ### end Alembic commands ###
