"""application user_id fix

Revision ID: 381cdcc9d333
Revises: ffc25d78dc6e
Create Date: 2026-10-03 21:27:50.403120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381cdcc9d333'
down_revision: Union[str, Sequence[str], None] = 'ffc25d78dc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_user_id_key'), 'applications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('applications_user_id_key'), 'applications', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
